export default {
    products: [
        {
            _id: '1',
            name: 'Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-1.jpg',
            price: 60,
            brand: 'hisskywin',
            rating: 4.5,
            numReviews: 10,
            countInstock: 6,
        },
        {
            _id: '2',
            name: '2Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-2.jpg',
            price: 60,
            brand: '2hisskywin',
            rating: 4.5,
            numReviews: 33,
            countInstock: 6,
        },
        {
            _id: '3',
            name: '3Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-3.jpg',
            price: 100,
            brand: 'hisskywin',
            rating: 4.5,
            numReviews: 133,
            countInstock: 6,
        },
        {
            _id: '4',
            name: '4Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-4.jpg',
            price: 60,
            brand: '44hisskywin',
            rating: 4.5,
            numReviews: 44,
            countInstock: 6,
        },
        {
            _id: '5',
            name: '5Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-5.jpg',
            price: 60,
            brand: 'hisskywin',
            rating: 4.5,
            numReviews: 10,
            countInstock: 6,
        },
        {
            _id: '6',
            name: '6Full Zip Running Shirts',
            category: 'Shirts',
            image:'/images/product-6.jpg',
            price: 60,
            brand: 'hisskywin',
            rating: 4.5,
            numReviews: 10,
            countInstock: 22,
        },
    ],
}